### ISSUE TITLE
ArgumentException thrown when invoked on a .PPTM or .PPTAM file

### ISSUE THREAD

**Issue by rajch** [mikeebowen/OOXML-Validator#1]
I got this exception while using the (excellent) OOXML Validator VS Code extension. The exact message was

```
Failed to run OOXML Validator. The error was: Unhandled exception. System.ArgumentException: file must be a .docx, .xlsx, or .pptx at OOXMLValidatorCLI.Classes.FunctionUtils.GetDocument(String filePath) in C:\source\OOXMLValidator\OOXMLValidatorCLI\Classes\FunctionUtils.cs:line 42 at OOXMLValidatorCLI.Classes.Validate.OOXML(String filePath, String format) in C:\source\OOXMLValidator\OOXMLValidatorCLI\Classes\Validate.cs:line 22 at OOXMLValidatorCLI.Program.Main(String[] args) in C:\source\OOXMLValidator\OOXMLValidatorCLI\Program.cs:line 20
```

The validator works well on .PPT and .PPTAM files, if they are renamed to .PPTX. So maybe the macro-enabled extensions could be allowed as well?

**Comment by mikeebowen** [comment]
Hi @rajch , Thanks for the suggestion. I like the idea and adding more allowed file types would be a simple change, but I'm not sure the validation is really correct. I have not worked with .PPTAM files, but I have worked with .PPT.  And .PPT files are in a binary file format while .PPTX are based on [Office Open XML (OOXML)](https://support.microsoft.com/en-us/office/open-xml-formats-and-file-name-extensions-5200d93c-3449-4380-8e11-31ef14555b18), which uses the [Open Package Convention](https://en.wikipedia.org/wiki/Open_Packaging_Conventions), so a .PPTX is a zip file with a lot of xml files in it that has a .pptx extension. The validator uses a wrapper around the [Open Xml SDK](https://github.com/OfficeDev/Open-XML-SDK) to validate those xml parts in the .pptx, .xlsx, or .docx file. I will have to check with that team to see if the validation works with other file types. 

When you validated the renamed .PPT and .PPTAM files did the validator find any errors or did it say the file was valid?

**Comment by rajch** [comment]
Hi @mikeebowen

It found the exact validation error that my buggy code had introduced, and helped me solve my problem.

A PPTM or PPTAM is just a PPTX with some extra elements. It’s still OOXML, and so the validator should work without any changes. I assume the same is true for XLSM, XLSAM, DOCM et al.

I’ll be happy to beta-test, if you make the change.

Thanks for an awesome pair or products.

Regards
Raj

**Comment by mikeebowen** [comment]
Hi @rajch , Thanks for the kind words :-) I spoke with the Open Xml SDK team and you're right, the SDK can make and validate XLSM, XLSAM, DOCM, etc., so the extension can validate them. The OOXML Validator VS Code Extension is where the code needs to change for this, so could you please make a request for the feature on the [repo for the OOXML Validator VS Code Extension issues page](https://github.com/mikeebowen/ooxml-validator-vscode/issues) and list all the file extensions you would like added. That will help me keep track of the feature and relate it to the commit that adds the feature. Thanks!

**Comment by mikeebowen** [comment]
Hi @rajch , update the extension to the latest and the validator will work on the additional file types.
