### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by kew-dev** [mikeebowen/OOXML-Validator#10]
Hi Mike! I have installed the OOXML Validator in VS Code, and I have opened a DOCX. However, when I right click I don't see the option to Validate OOXML as is shown in the "Usage Details" screen captures for the extension in VS Code. Can you please tell me what I might be missing? Thank you.

**Comment by mikeebowen** [comment]
Hi @kew-dev , When this happens, click on a different file then right-click on the file you want to validate. The Validate option should show then. This is an issue with VS Code and context menu extensions that I haven't figured out how to fix other than clicking on a different file. FYI, this repo is for the cli validator the extension uses not the extension itself. The repo for the extension is here: [OOXML Validator VS Code](https://github.com/mikeebowen/ooxml-validator-vscode)
