### ISSUE TITLE
[FEATURE] Non-CLI calling of Validator.OOXML()

### ISSUE THREAD

**Issue by ashahabov** [mikeebowen/OOXML-Validator#11]
Would be awesome to have some **library** build of this validator, to be able to call `Validator.OOXML()` inside of unit test project.

For example, I changed pptx-file by Open XML SDK, then wanna check whether the changes broke the presentation structure.

I believe using CLI version in unit test project is also possible, but a library type artifact would be better, especially for cross-platform testing.

**Comment by mikeebowen** [comment]
The validator uses the Open XML SDK to do the validation, so you can use the OOXML SDK itself to validate package structure in your tests. To validate a file with the SDK you use the [OpenXmlValidator Class](https://learn.microsoft.com/en-us/dotnet/api/documentformat.openxml.validation.openxmlvalidator?view=openxml-2.8.1), similar to this:

```csharp
using (SpreadsheetDocument spreadsheet = SpreadsheetDocument.Open(filePath, true))
{
    OpenXmlValidator openXmlValidator = new OpenXmlValidator(FileFormatVersions.Microsoft365);

    var errors = openXmlValidator.Validate(spreadsheet);
}
```

`errors` wil be an IEnumerable of the validation errors.

**Comment by AdamShakhabov** [comment]
Wow😯 I didn't know. I somehow missed `OpenXmlValidator`. Thank you!
