### ISSUE TITLE
Error message about non existing part should give details about the part names (source and target)

### ISSUE THREAD

**Issue by programaths** [mikeebowen/OOXML-Validator#20]
When validating a document, we can get this error message:

`[{"Description":"Specified part does not exist in the package.","Path":null,"Id":null,"ErrorType":"OpenXmlPackageException"}]`

That would be better if it could give the source and target part so we know what to fix.

**Comment by mikeebowen** [comment]
Hi @programaths, this project is a wrapper around the [Open-XML-SDK](https://github.com/dotnet/Open-XML-SDK)'s validator functionality, it's formatting the data and returning it in a way that [ooxml-validator-vscode](https://github.com/mikeebowen/ooxml-validator-vscode) can use and can only return what it receives from the Open-XML-SDK. Any changes would have to be made in the Open-XML-SDK's repo then the OOXML-Validator would pick up those changes.
