### ISSUE TITLE
Error when trying to run on Ubuntu

### ISSUE THREAD

**Issue by ajitpeter** [mikeebowen/OOXML-Validator#21]
I am trying to run v2.1.3 of the release on an Ubuntu 22.04 machine. I get an error while trying to run the application. I am using the prebuilt app from linux-x64. 

This is the error message that I get -
```
ajit@ajit-virtual-machine:~/Downloads$ ./OOXMLValidatorCLI
The application to execute does not exist: '/home/ajit/Downloads/OOXMLValidatorCLI.dll'.
```

**Comment by mikeebowen** [comment]
Do you have .NET installed?

**Comment by ajitpeter** [comment]
No, I don't have it installed originally as it was a vanilla VM. I switched to using VS code extension of the tool and it did install it and I was able to run the check on my ubuntu machine. I tried the standalone app again and I got the same error message.

**Comment by mikeebowen** [comment]
How are you downloading the Validator? Are you cloning it or downloading it from the release page?

**Comment by ajitpeter** [comment]
I downloaded it from the release page.

**Comment by mikeebowen** [comment]
That should be self-contained. I will find a Linux machine and see if I can find the issue.

**Comment by ajitpeter** [comment]
Thank you very much.

**Comment by orangemug** [comment]
@mikeebowen I'm also experiencing a simular issue. Using a docker container might be your best bet for easy testing, that's how I experienced the issue, run with `docker run -it --platform=linux/amd64 ubuntu bash` and fetching the required dependencies

```
# ./OOXMLValidatorCLI 
The application to execute does not exist: '/OOXMLValidatorCLI.dll'.
```

I'd like to add this to our CI as a part of an automated build process, so linux is really important for that. Is there any work around? Maybe install some library?

I'm not a C# person, but any other way I can help out let me know (testing, ci/github-actions setup maybe??).
