### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by Asbjoedt** [mikeebowen/OOXML-Validator#8]
Hello!

Thanks for the new directory analysis function.

I tried testing the directory analysis on a directory with 16.000 spreadsheets (a large portion of which is XLS, so the real number of XLSX is much smaller).

Command line gave me the following error and the created XML output file is empty.

> Unhandled exception. System.IO.InvalidDataException: End of Central Directory record could not be found.
>    at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
>    at System.IO.Compression.ZipArchive..ctor(Stream , ZipArchiveMode , Boolean , Encoding )
>    at System.IO.Packaging.ZipPackage..ctor(String path, FileMode packageFileMode, FileAccess packageFileAccess, FileShare share)
>    at System.IO.Packaging.Package.Open(String path, FileMode packageMode, FileAccess packageAccess, FileShare packageShare)
>    at DocumentFormat.OpenXml.Packaging.PackageLoader.OpenCore(String path, Boolean readWriteMode)
>    at DocumentFormat.OpenXml.Packaging.SpreadsheetDocument.Open(String path, Boolean isEditable, OpenSettings openSettings)
>    at OOXMLValidatorCLI.Classes.FunctionUtils.GetDocument(String filePath, String fileExtension)
>    at OOXMLValidatorCLI.Classes.Validate.OOXML(String filePath, String format, Boolean returnXml, Boolean recursive)
>    at OOXMLValidatorCLI.Program.Main(String[] args)

I tried testing the same sample base but only including files 3MB or less. The sample size was approx. 15.000 spreadsheets. I got the same error.

I tried putting th first 500 spreadsheets in their own folder and run the test. I got the following error.

> Unhandled exception. DocumentFormat.OpenXml.Packaging.OpenXmlPackageException: A malformed URI was found in the document. Please provide a OpenSettings.RelationshipErrorRewriter to handle these errors while opening a package.
>  ---> System.UriFormatException: Invalid URI: The hostname could not be parsed.
>    at System.Uri.CreateThis(String , Boolean , UriKind , UriCreationOptions& )
>    at System.Uri..ctor(String uriString, UriKind uriKind)
>    at System.IO.Packaging.InternalRelationshipCollection.ProcessRelationshipAttributes(XmlCompatibilityReader reader)
>    at System.IO.Packaging.InternalRelationshipCollection.ParseRelationshipPart(PackagePart part)
>    at System.IO.Packaging.InternalRelationshipCollection..ctor(Package package, PackagePart part)
>    at System.IO.Packaging.PackagePart.EnsureRelationships()
>    at DocumentFormat.OpenXml.Packaging.OpenXmlPart.Load(OpenXmlPackage openXmlPackage, OpenXmlPart parent, Uri uriTarget, String id, Dictionary`2 loadedParts)
>    at DocumentFormat.OpenXml.Packaging.OpenXmlPartContainer.LoadReferencedPartsAndRelationships(OpenXmlPackage openXmlPackage, OpenXmlPart sourcePart, RelationshipCollection relationshipCollection, Dictionary`2 loadedParts)
>    at DocumentFormat.OpenXml.Packaging.OpenXmlPartContainer.LoadReferencedPartsAndRelationships(OpenXmlPackage openXmlPackage, OpenXmlPart sourcePart, RelationshipCollection relationshipCollection, Dictionary`2 loadedParts)
>    at DocumentFormat.OpenXml.Packaging.OpenXmlPackage.Load(Package package)
>    --- End of inner exception stack trace ---
>    at DocumentFormat.OpenXml.Packaging.OpenXmlPackage.Load(Package package)
>    at DocumentFormat.OpenXml.Packaging.SpreadsheetDocument.Open(String path, Boolean isEditable, OpenSettings openSettings)
>    at OOXMLValidatorCLI.Classes.FunctionUtils.GetDocument(String filePath, String fileExtension)
>    at OOXMLValidatorCLI.Classes.Validate.OOXML(String filePath, String format, Boolean returnXml, Boolean recursive)
>    at OOXMLValidatorCLI.Program.Main(String[] args)

I am not using recursive function.

**Comment by mikeebowen** [comment]
Hi @Asbjoedt ,

I tested the `.exe` on my PC and didn't get any exceptions, but I didn't try Mac or Linux. What operating system are you using?

**Comment by Asbjoedt** [comment]
Hello

I am using Windows and the Win exe.

I tried using another data sample today and i got same error. If I exclude --recursive argument, then files in the first/root directory are properly validated.

```
Unhandled exception. System.IO.InvalidDataException: End of Central Directory record could not be found.
at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
at System.IO.Compression.ZipArchive..ctor(Stream , ZipArchiveMode , Boolean , Encoding )
at System.IO.Packaging.ZipPackage..ctor(String path, FileMode packageFileMode, FileAccess packageFileAccess, FileShare share)
at System.IO.Packaging.Package.Open(String path, FileMode packageMode, FileAccess packageAccess, FileShare packageShare)
at DocumentFormat.OpenXml.Packaging.PackageLoader.OpenCore(String path, Boolean readWriteMode)
at DocumentFormat.OpenXml.Packaging.SpreadsheetDocument.Open(String path, Boolean isEditable, OpenSettings openSettings)
at OOXMLValidatorCLI.Classes.FunctionUtils.GetDocument(String filePath, String fileExtension)
at OOXMLValidatorCLI.Classes.Validate.OOXML(String filePath, String format, Boolean returnXml, Boolean recursive)
at OOXMLValidatorCLI.Program.Main(String[] args)
```

I am using the data sample, you can download from here. It is a bunch of spreadsheets in different file formats: https://github.com/Asbjoedt/CLISC/tree/master/Test_Data

**Comment by Asbjoedt** [comment]
I found this: https://stackoverflow.com/questions/28764138/read-xlsx-excel-file-error

If there's a password protected file this exception happens (i think) because you can't open them even just to find if the package is valid or the file is strict.

Do you think this is it?

**Comment by mikeebowen** [comment]
Hi @Asbjoedt ,

Thanks for the spreadsheet samples, I'll try them to see if it changes the results. Currently, I am able to reproduce the invalid Int32 issue with a new unprotected spreadsheet, so I don't think it's the password causing the problem. I think I have found the issue, but it's in a generated file, so fixing it is not as straightforward as I would have hoped. I will update you with any progress.

**Comment by mikeebowen** [comment]
Hi @Asbjoedt ,

I confused this with your other issue, sorry about that. Please disregard my previous post (I deleted it). For this issue, when you run the CLI on the folder, do you know that some of the files are password protected?

**Comment by Asbjoedt** [comment]
NP.

Yes, there are password protected files.

**Comment by mikeebowen** [comment]
Hi @Asbjoedt ,

I have refactored the validator the validator to handle `OpenXmlPackageException` exceptions that prevent the SDK from opening the file at all, e.g. a password protected file or a file that is extremely non-conformant. 

I also added a `-a` or `--all` flag that will include valid files in the returned XML. If it is not included, only files with errors will be returned. 

You can download the binary for your system from the [Release Page](https://github.com/mikeebowen/OOXML-Validator/releases/tag/v2.0.0).

The xml format has changed. the Document element now contains `File` elements. the FilePath and the IsStrict attributes  are now on the File element. The File element contains a `<ValidationErrorInfoList />` element that contains the ValidationErrorInfo elements or a `<Exceptions />` element that contains information about the OpenXmlPackageException exception that prevented the file from opening. 

An example of a File element with a OpenXmlPackageException:

```xml
<File FilePath="C:\source\deleteThis\Test_Data\Test_Data\Another folder\Invalid spreadsheet package.xlsx"
    IsStrict="false">
  <Exceptions>
    <OpenXmlPackageException>
      <Message>The specified package is invalid. The main part is missing.</Message>
    </OpenXmlPackageException>
  </Exceptions>
</File>
```

and with a ValidationErrorInfoList element for a file with no validation errors: 

```xml
<File FilePath="C:\source\deleteThis\Test_Data\Test_Data\Another folder\With data connection.xlsx" IsStrict="false">
  <ValidationErrorInfoList />
</File>
```

Some of the OpenXmlPackageException messages are more helpful than others. E.g. "The specified package is invalid. The main part is missing." means exactly what it sounds like: there is no main part, so the SDK can't open the file. But when a file is password protected the message is "End of Central Directory record could not be found.", which is less helpful. These are messages from the SDK, so the CLI only passes along the information.

I am able to run the Validator CLI on the sample folder you sent and handle all of the files without throwing errors, so I will close this issue. Please post any additional issues you run into.
